"""create hardened governance schema

Revision ID: f4a07a376d4e
Revises:
"""

import sqlalchemy as sa
from alembic import op

revision = "f4a07a376d4e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("user_reference", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("agent_reference", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource", sa.String(length=250), nullable=False),
        sa.Column("result", sa.String(length=50), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=True),
        sa.Column("policy_reference", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_logs_action_timestamp", "audit_logs", ["action", "timestamp"], unique=False
    )
    op.create_index(
        "ix_audit_logs_agent_timestamp",
        "audit_logs",
        ["agent_reference", "timestamp"],
        unique=False,
    )
    op.create_index(op.f("ix_audit_logs_timestamp"), "audit_logs", ["timestamp"], unique=False)
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_user_reference"), "audit_logs", ["user_reference"], unique=False
    )
    op.create_index(
        "ix_audit_logs_user_timestamp", "audit_logs", ["username", "timestamp"], unique=False
    )
    op.create_table(
        "policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column(
            "effect",
            sa.Enum("ALLOW", "DENY", "CONDITIONAL", name="policyeffect", native_enum=False),
            nullable=False,
        ),
        sa.Column("resource", sa.String(length=200), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("conditions", sa.JSON(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_policies_action"), "policies", ["action"], unique=False)
    op.create_index(op.f("ix_policies_enabled"), "policies", ["enabled"], unique=False)
    op.create_index(
        "ix_policies_evaluation",
        "policies",
        ["enabled", "action", "resource", "priority", "effect", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_policies_priority"), "policies", ["priority"], unique=False)
    op.create_index(op.f("ix_policies_resource"), "policies", ["resource"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "OPERATOR", "AUDITOR", "VIEWER", name="role", native_enum=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "agents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("agent_type", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ENABLED", "DISABLED", "SUSPENDED", name="agentstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agents_name"), "agents", ["name"], unique=True)
    op.create_index(op.f("ix_agents_owner_id"), "agents", ["owner_id"], unique=False)
    op.create_index(op.f("ix_agents_status"), "agents", ["status"], unique=False)
    op.create_table(
        "permissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["policy_id"], ["policies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "policy_id"),
    )
    op.create_index(op.f("ix_permissions_agent_id"), "permissions", ["agent_id"], unique=False)
    op.create_index(op.f("ix_permissions_policy_id"), "permissions", ["policy_id"], unique=False)
    op.create_table(
        "spend_limits",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column(
            "period",
            sa.Enum("DAILY", "MONTHLY", "TRANSACTION", name="limitperiod", native_enum=False),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "period", "currency"),
    )
    op.create_index(op.f("ix_spend_limits_agent_id"), "spend_limits", ["agent_id"], unique=False)
    op.create_table(
        "spend_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_spend_records_agent_currency_timestamp",
        "spend_records",
        ["agent_id", "currency", "timestamp"],
        unique=False,
    )
    op.create_index(op.f("ix_spend_records_agent_id"), "spend_records", ["agent_id"], unique=False)
    op.create_index(
        op.f("ix_spend_records_timestamp"), "spend_records", ["timestamp"], unique=False
    )
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """
            CREATE FUNCTION prevent_audit_log_mutation() RETURNS trigger
            LANGUAGE plpgsql AS $$
            BEGIN
                RAISE EXCEPTION 'audit_logs are immutable';
            END;
            $$;
            """
        )
        op.execute(
            """
            CREATE TRIGGER audit_logs_immutable
            BEFORE UPDATE OR DELETE ON audit_logs
            FOR EACH ROW EXECUTE FUNCTION prevent_audit_log_mutation();
            """
        )
    elif op.get_bind().dialect.name == "sqlite":
        op.execute(
            """
            CREATE TRIGGER audit_logs_no_update
            BEFORE UPDATE ON audit_logs
            BEGIN SELECT RAISE(ABORT, 'audit_logs are immutable'); END;
            """
        )
        op.execute(
            """
            CREATE TRIGGER audit_logs_no_delete
            BEFORE DELETE ON audit_logs
            BEGIN SELECT RAISE(ABORT, 'audit_logs are immutable'); END;
            """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER audit_logs_immutable ON audit_logs")
        op.execute("DROP FUNCTION prevent_audit_log_mutation()")
    elif op.get_bind().dialect.name == "sqlite":
        op.execute("DROP TRIGGER audit_logs_no_update")
        op.execute("DROP TRIGGER audit_logs_no_delete")
    op.drop_index(op.f("ix_spend_records_timestamp"), table_name="spend_records")
    op.drop_index(op.f("ix_spend_records_agent_id"), table_name="spend_records")
    op.drop_index("ix_spend_records_agent_currency_timestamp", table_name="spend_records")
    op.drop_table("spend_records")
    op.drop_index(op.f("ix_spend_limits_agent_id"), table_name="spend_limits")
    op.drop_table("spend_limits")
    op.drop_index(op.f("ix_permissions_policy_id"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_agent_id"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_agents_status"), table_name="agents")
    op.drop_index(op.f("ix_agents_owner_id"), table_name="agents")
    op.drop_index(op.f("ix_agents_name"), table_name="agents")
    op.drop_table("agents")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_policies_resource"), table_name="policies")
    op.drop_index(op.f("ix_policies_priority"), table_name="policies")
    op.drop_index("ix_policies_evaluation", table_name="policies")
    op.drop_index(op.f("ix_policies_enabled"), table_name="policies")
    op.drop_index(op.f("ix_policies_action"), table_name="policies")
    op.drop_table("policies")
    op.drop_index("ix_audit_logs_user_timestamp", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_user_reference"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_timestamp"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_agent_timestamp", table_name="audit_logs")
    op.drop_index("ix_audit_logs_action_timestamp", table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
