import type { SystemSubmission } from "./types";

export const demoSystems: SystemSubmission[] = [
  {
    systemName: "Healthcare Diagnostic AI",
    organization: "Northstar Health",
    industry: "Healthcare",
    modelType: "Deep learning",
    deploymentType: "Private cloud",
    region: "European Union",
    description: "Clinical decision support using medical imaging and patient history.",
    intendedUse: "Assist radiologists with diagnosis; a clinician confirms every result.",
    trainingDataSource: "De-identified partner hospital datasets",
    dataCategories: "Medical images, health records, demographics",
    sensitiveData: "Yes",
    humanOversight: "Yes",
  },
  {
    systemName: "Credit Scoring System",
    organization: "Fjord Financial",
    industry: "Financial services",
    modelType: "Gradient boosted model",
    deploymentType: "Public cloud API",
    region: "United States",
    description: "Automated credit risk scoring for consumer lending applications.",
    intendedUse: "Recommend credit eligibility, interest band, and manual review route.",
    trainingDataSource: "Credit bureau and consented transaction history",
    dataCategories: "Financial history, demographics, identity data",
    sensitiveData: "Yes",
    humanOversight: "Yes",
  },
  {
    systemName: "Hiring Assistant",
    organization: "Valhalla People",
    industry: "Human resources",
    modelType: "Natural language processing",
    deploymentType: "SaaS",
    region: "United Kingdom",
    description: "Ranks candidates from resumes and structured interview responses.",
    intendedUse: "Shortlist applicants for employment decisions.",
    trainingDataSource: "Historical recruitment outcomes",
    dataCategories: "Employment history, education, demographics",
    sensitiveData: "Yes",
    humanOversight: "No",
  },
  {
    systemName: "Facial Recognition Platform",
    organization: "Heimdall Vision",
    industry: "Security",
    modelType: "Neural biometric model",
    deploymentType: "Edge and public cloud",
    region: "European Union",
    description: "Facial biometric identification for access and public security.",
    intendedUse: "Match live camera subjects against identity records.",
    trainingDataSource: "Licensed facial image datasets",
    dataCategories: "Biometrics, identity, location",
    sensitiveData: "Yes",
    humanOversight: "No",
  },
  {
    systemName: "Customer Support Chatbot",
    organization: "Rune Commerce",
    industry: "Retail",
    modelType: "Large language model",
    deploymentType: "Public cloud",
    region: "Global",
    description: "Conversational support for order status and product questions.",
    intendedUse: "Resolve routine customer queries and escalate complex cases.",
    trainingDataSource: "Approved help center and anonymized support transcripts",
    dataCategories: "Contact details, order history",
    sensitiveData: "No",
    humanOversight: "Yes",
  },
  {
    systemName: "Autonomous Vehicle Controller",
    organization: "Bifrost Mobility",
    industry: "Automotive",
    modelType: "Multi-modal neural network",
    deploymentType: "Vehicle edge",
    region: "United States",
    description: "Real-time autonomous vehicle perception and driving control.",
    intendedUse: "Control steering, braking, and navigation in designated operating areas.",
    trainingDataSource: "Fleet sensor data and simulation",
    dataCategories: "Video, lidar, telemetry, location",
    sensitiveData: "Yes",
    humanOversight: "No",
  },
];
